### ISSUE TITLE
Convert to python3-opensearch-py

### ISSUE THREAD

**Issue by arlake228** [perfsonar/elmond#11]
The elasticsearch client library seems to be doing some checks that break compatibility with OpenSearch. We should switch to python3-opensearch-py. It is in EPEL for EL9, but I have not checked other repo.

**Comment by arlake228** [comment]
I created a branch with  the change. Just switching the import and constructor works with no other changes. The package is available in EPEL for EL8 and EL8. I don't see it on Ubuntu 20 or EL7. I have not checked Debian. We have a couple options:

1. Build the opensearch-py package for the OSes that are missing it. We already do this for python3-elasticsearch.
2. Patch some OSes to use Elasticsearch and some to use opensearch. Many have an older Elasticsearch plugin where this is not an issue.

Likely option 1 makes most sense.

**Comment by laeti-tia** [comment]
Yes, I guess we can package that for the missing OS.  I don't see anything for OpenSearch in the Debian or Ubuntu repos.
