### ISSUE TITLE
elmond tries to query rollup indices

### ISSUE THREAD

**Issue by sowmyab** [perfsonar/elmond#6]
When perfsonar-graphs query for latency and packet loss, elmond tries to query the rollup index and returns empty results. 

There is a isRollUp flag in the code that gets set to 'true' when the aggregation endpoints are hit. This needs to be set to false so elmond can query the data index.
Also, the field-name mappings, that refer to the rollup indices need to be updated to match the field-names in the data index. (The mappings can be found at the beginning of the data.py file)

**Comment by arlake228** [comment]
This is fixed, it now uses aggregations in queries to achieve same result.
