### ISSUE TITLE
Modify or remove default summary window option in config file

### ISSUE THREAD

**Issue by sowmyab** [perfsonar/elmond#7]
The elmond.json config file has a default summary option. This causes elmond to generate only the summaries specified (throughput and packet-loss). So, when the graphs try to query latency data, it does not return expected response and therefore, the graphs do not display latency data. 

Leaving the option empty generates the correct summaries in output and graphs are able to display the data.
`"SUMMARIES": {}`

**Comment by arlake228** [comment]
Elmond now supports the full set of summaries using aggregations at query time. I have removed this config completely and it now just uses defaults.
